name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: |
          
          pip install django

      - name: Rodar testes
        run: |
          cd projeto
          cd calcmusic

          python manage.py test